FROM python:3.9

WORKDIR /SmashTheOdds

COPY . .

ARG REQUIREMENTS


RUN pip install --no-cache-dir -r "$REQUIREMENTS"

CMD ["sh", "-c", "sleep 10 && python3 -m pytest tests/test_api.py 2>&1 | tee -a $LOG_PYTEST"]

