FROM python:3.9

WORKDIR /SmashTheOdds

COPY . .

RUN pip install --no-cache-dir -r api/requirements_api.txt

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "api.api_main:app", "--reload", "--host", "0.0.0.0"]